### ISSUE TITLE
Disable drift music/sound?

### ISSUE THREAD

**Issue by mathamer** [SoulMaril/wt-betty#1]
Wondering if there is way to **disable** drift music since is kinda **annoying** :(

**Comment by SoulMaril** [comment]
Hey There, I have abandoned this code for a long time. I dont remember
clearly but as far as I remember you can simply untick the effect from the
options menu. I don't remember a drift music but there were 3 sound effect;
G-Force, Angle of Attack and Landing Gear Warning.

**Comment by mathamer** [comment]
Awh, sorry.. but this is the thing that bothers me and there is no setting to turn it off.

![Screenshot 2020-12-23 115944](https://user-images.githubusercontent.com/58902846/102989718-602b9c80-4516-11eb-90e9-46991228cfd7.png)

https://user-images.githubusercontent.com/58902846/102989578-265a9600-4516-11eb-8ff5-943771bdd91d.mp4

**Comment by mathamer** [comment]
I'm sorry, yeah.. it's someones else version of app :(

**Comment by SoulMaril** [comment]
Hi, Looks like you are using a Fork. This is not mine. I haven't added such
an irrelevant sound like that.
Go to my github repo and try downloading my original work from
https://github.com/SoulMaril/wt-betty

Have a nice day.
